pipeline {
    agent any

    environment {
        SERVICE_NAME = 'order-service' // ⬅ Change to product-service or order-service as needed
        DOCKER_USERNAME = 'avinash8476'
        DOCKER_IMAGE = "${DOCKER_USERNAME}/${SERVICE_NAME}:${BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', credentialsId: 'ecmp-apps-uat', url: 'https://github.com/avinash2354/ecmp-apps-uat.git'
            echo "git repo clone  successfully"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}", "./${SERVICE_NAME}") 
                    echo "Docker image built successfully"
                }
            }
        }    
    }

}
