pipeline {
    agent any

    environment {
        SERVICE_NAME = 'auth-service'   // change for product-service / order-service
        DOCKER_USERNAME = 'avinash8476'
        DOCKER_IMAGE = "${DOCKER_USERNAME}/${SERVICE_NAME}:${BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', credentialsId: 'ecmp-apps-uat', url: 'https://github.com/avinash2354/ecmp-apps-uat.git'
            echo "git repo clone  successfully"
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}", "./${SERVICE_NAME}") 	
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-pass', 
                                                    passwordVariable: 'dockerHubPassword', 
                                                    usernameVariable: 'dockerHubUser')]) {
                        sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                        sh "docker push ${DOCKER_IMAGE}"
                        sh "docker logout" // Optional, but good practice
                    }
                }
            }
        }
    }
}

