pipeline {
    agent any

    environment {
        SERVICE_NAME = 'auth-service' // ⬅ Change to product-service or order-service as needed
        DOCKER_USERNAME = 'avinash8476'
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGE = "${DOCKER_USERNAME}/${SERVICE_NAME}:${IMAGE_TAG}"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', credentialsId: 'ecmp-apps-uat', url: 'https://github.com/avinash2354/ecmp-apps-uat.git'
            echo "git repo clone  successfully"              
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🔨 Building Docker image  for ${SERVICE_NAME}..."
                docker build -t ${DOCKER_IMAGE} ./${SERVICE_NAME}
                echo "🔨 Image built successfully"
            }
        }

        stage('Push Docker Image') {
            steps {
                echo "🔐 Authenticating with Docker Hub..."
                withCredentials([usernamePassword(credentialsId: 'dockerhub-pass', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin'
                    echo "🚀 Pushing image: ${DOCKER_IMAGE}"
                    sh "docker push ${DOCKER_IMAGE}"
                }
            }
        }   
    }
}
